# Generated by Django 4.1.7 on 2023-02-28 11:58

from django.db import migrations, models
import django.db.models.deletion
#import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Cour',
                'verbose_name_plural': 'Cours',
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Filiere',
                'verbose_name_plural': 'Filieres',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.ImageField(unique=True, upload_to=None)),
                #('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('birthdate', models.DateField()),
                ('filiere_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Etudiants.filiere', verbose_name='')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(max_length=2)),
                ('cour_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Etudiants.cour', verbose_name='')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Etudiants.student', verbose_name='')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
        migrations.AddField(
            model_name='cour',
            name='filiere_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Etudiants.filiere', verbose_name=''),
        ),
    ]
