# Generated by Django 4.1.7 on 2023-02-28 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiants', '0002_alter_student_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cour',
            old_name='filiere_id',
            new_name='filiere',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='cour_id',
            new_name='cour',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='filiere_Id',
            new_name='filiere',
        ),
    ]
