# Generated by Django 4.1.7 on 2023-03-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiants', '0004_rename_filiere_cour_filiere_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
