# Generated by Django 4.1.7 on 2023-03-02 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiants', '0005_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
